import dynamic_renormalization_group_methods_applied_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace dynamic_renormalization_group_methods_applied_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end dynamic_renormalization_group_methods_applied_theorem_canonical_lane_mathlib
end HautevilleHouse
